name: build-caffe-2
on:
  push:
    branches:
      - 'caffe'
  workflow_dispatch:

# Add necessary permissions for the GITHUB_TOKEN
permissions:
  contents: write
  actions: read

env:
  WINE_VERSION: 10.8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: setup
        working-directory: /home/runner/work/
        run: |
          sudo apt purge -y ubuntu-advantage-tools python3-update-manager
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          
      - name: clone wine-tkg-git repo
        working-directory: /home/runner/work/
        run: git clone https://github.com/Frogging-Family/wine-tkg-git.git
        
      - name: get/set the caffe recipe
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/
        run: |
          curl https://raw.githubusercontent.com/bottlesdevs/build-tools/main/runners/vaniglia/wine-tkg.cfg >> customization.cfg
          sed -i "s/_staging_version=\"\"/_staging_version=\"v$WINE_VERSION\"/g" customization.cfg
          sed -i "s/_plain_version=\"\"/_plain_version=\"wine-$WINE_VERSION\"/g" customization.cfg
          
      - name: start build
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/
        run: yes|./non-makepkg-build.sh
        
      - name: package
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/non-makepkg-builds/
        run: |
          mv wine-tkg-staging-* caffe-$WINE_VERSION-x86_64
          tar cJvf caffe-$WINE_VERSION-x86_64.tar.xz caffe-$WINE_VERSION-x86_64
          # Copy to both /tmp and workspace for artifacts
          mv caffe-$WINE_VERSION-x86_64.tar.xz /tmp/caffe-$WINE_VERSION-x86_64.tar.xz
          cp /tmp/caffe-$WINE_VERSION-x86_64.tar.xz ${{ github.workspace }}/caffe-$WINE_VERSION-x86_64.tar.xz
          
      # Upload artifacts (alternative to releases)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: caffe-${{ env.WINE_VERSION }}-x86_64
          path: caffe-${{ env.WINE_VERSION }}-x86_64.tar.xz
          retention-days: 30
          
      # Create release (with proper permissions)
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: "caffe-${{ env.WINE_VERSION }}"
          title: "Caffe ${{ env.WINE_VERSION }}"
          files: "/tmp/caffe-${{ env.WINE_VERSION }}-x86_64.tar.xz"
